version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: credito_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: credito_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d credito_api"]
      interval: 10s
      timeout: 5s
      retries: 5

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: credito_zookeeper
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: credito_kafka
    restart: unless-stopped
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    ports:
      - "9092:9092"
      - "9094:9094"

  api:
    build:
      context: .
      dockerfile: src/CreditoApi/Dockerfile
    container_name: credito_api
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__CreditoApiDatabase: Host=postgres;Port=5432;Database=credito_api;Username=postgres;Password=postgres
      Kafka__BootstrapServers: kafka:9092
      Kafka__ConsumerGroupId: credito-api-group
      Kafka__Creditos__EntryTopic: integrar-credito-constituido-entry
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started

  worker:
    build:
      context: .
      dockerfile: src/CreditoApi.Worker/Dockerfile
    container_name: credito_worker
    restart: unless-stopped
    environment:
      ConnectionStrings__CreditoApiDatabase: Host=postgres;Port=5432;Database=credito_api;Username=postgres;Password=postgres
      Kafka__BootstrapServers: kafka:9092
      Kafka__ConsumerGroupId: credito-api-worker
      Kafka__Creditos__EntryTopic: integrar-credito-constituido-entry
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started

volumes:
  postgres_data:
